package com.nuu.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nuu.db.bean.Devices;

import com.nuu.db.dao.DevicesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig devicesDaoConfig;

    private final DevicesDao devicesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        devicesDaoConfig = daoConfigMap.get(DevicesDao.class).clone();
        devicesDaoConfig.initIdentityScope(type);

        devicesDao = new DevicesDao(devicesDaoConfig, this);

        registerDao(Devices.class, devicesDao);
    }
    
    public void clear() {
        devicesDaoConfig.clearIdentityScope();
    }

    public DevicesDao getDevicesDao() {
        return devicesDao;
    }

}
