// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_response.proto

package com.nuu.proto;

public final class ServerResponse {
    private ServerResponse() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ReportDeviceStatusInfoRespOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.nuu.proto.ReportDeviceStatusInfoResp)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string device_id = 1;</code>
         */
        boolean hasDeviceId();

        /**
         * <code>optional string device_id = 1;</code>
         */
        String getDeviceId();

        /**
         * <code>optional string device_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getDeviceIdBytes();

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        boolean hasUtc();

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        int getUtc();
    }

    /**
     * Protobuf type {@code com.nuu.proto.ReportDeviceStatusInfoResp}
     */
    public static final class ReportDeviceStatusInfoResp extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.nuu.proto.ReportDeviceStatusInfoResp)
            ReportDeviceStatusInfoRespOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ReportDeviceStatusInfoResp.newBuilder() to construct.
        private ReportDeviceStatusInfoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ReportDeviceStatusInfoResp() {
            deviceId_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ReportDeviceStatusInfoResp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            deviceId_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            utc_ = input.readUInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ServerResponse.internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ServerResponse.internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ReportDeviceStatusInfoResp.class, Builder.class);
        }

        private int bitField0_;
        public static final int DEVICE_ID_FIELD_NUMBER = 1;
        private volatile Object deviceId_;

        /**
         * <code>optional string device_id = 1;</code>
         */
        public boolean hasDeviceId() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional string device_id = 1;</code>
         */
        public String getDeviceId() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    deviceId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string device_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int UTC_FIELD_NUMBER = 2;
        private int utc_;

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        public boolean hasUtc() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        public int getUtc() {
            return utc_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeUInt32(2, utc_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, utc_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ReportDeviceStatusInfoResp)) {
                return super.equals(obj);
            }
            ReportDeviceStatusInfoResp other = (ReportDeviceStatusInfoResp) obj;

            if (hasDeviceId() != other.hasDeviceId()) return false;
            if (hasDeviceId()) {
                if (!getDeviceId()
                        .equals(other.getDeviceId())) return false;
            }
            if (hasUtc() != other.hasUtc()) return false;
            if (hasUtc()) {
                if (getUtc()
                        != other.getUtc()) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasDeviceId()) {
                hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
                hash = (53 * hash) + getDeviceId().hashCode();
            }
            if (hasUtc()) {
                hash = (37 * hash) + UTC_FIELD_NUMBER;
                hash = (53 * hash) + getUtc();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ReportDeviceStatusInfoResp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ReportDeviceStatusInfoResp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ReportDeviceStatusInfoResp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ReportDeviceStatusInfoResp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ReportDeviceStatusInfoResp prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.nuu.proto.ReportDeviceStatusInfoResp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.nuu.proto.ReportDeviceStatusInfoResp)
                ReportDeviceStatusInfoRespOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ServerResponse.internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ServerResponse.internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ReportDeviceStatusInfoResp.class, Builder.class);
            }

            // Construct using com.nuu.proto.ServerResponse.ReportDeviceStatusInfoResp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                deviceId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                utc_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ServerResponse.internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_descriptor;
            }

            @Override
            public ReportDeviceStatusInfoResp getDefaultInstanceForType() {
                return ReportDeviceStatusInfoResp.getDefaultInstance();
            }

            @Override
            public ReportDeviceStatusInfoResp build() {
                ReportDeviceStatusInfoResp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public ReportDeviceStatusInfoResp buildPartial() {
                ReportDeviceStatusInfoResp result = new ReportDeviceStatusInfoResp(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.deviceId_ = deviceId_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.utc_ = utc_;
                    to_bitField0_ |= 0x00000002;
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ReportDeviceStatusInfoResp) {
                    return mergeFrom((ReportDeviceStatusInfoResp) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ReportDeviceStatusInfoResp other) {
                if (other == ReportDeviceStatusInfoResp.getDefaultInstance()) return this;
                if (other.hasDeviceId()) {
                    bitField0_ |= 0x00000001;
                    deviceId_ = other.deviceId_;
                    onChanged();
                }
                if (other.hasUtc()) {
                    setUtc(other.getUtc());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ReportDeviceStatusInfoResp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ReportDeviceStatusInfoResp) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Object deviceId_ = "";

            /**
             * <code>optional string device_id = 1;</code>
             */
            public boolean hasDeviceId() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public String getDeviceId() {
                Object ref = deviceId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        deviceId_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getDeviceIdBytes() {
                Object ref = deviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    deviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public Builder setDeviceId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                deviceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public Builder clearDeviceId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                deviceId_ = getDefaultInstance().getDeviceId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public Builder setDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                deviceId_ = value;
                onChanged();
                return this;
            }

            private int utc_;

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public boolean hasUtc() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public int getUtc() {
                return utc_;
            }

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public Builder setUtc(int value) {
                bitField0_ |= 0x00000002;
                utc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public Builder clearUtc() {
                bitField0_ = (bitField0_ & ~0x00000002);
                utc_ = 0;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.nuu.proto.ReportDeviceStatusInfoResp)
        }

        // @@protoc_insertion_point(class_scope:com.nuu.proto.ReportDeviceStatusInfoResp)
        private static final ReportDeviceStatusInfoResp DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ReportDeviceStatusInfoResp();
        }

        public static ReportDeviceStatusInfoResp getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<ReportDeviceStatusInfoResp>
                PARSER = new com.google.protobuf.AbstractParser<ReportDeviceStatusInfoResp>() {
            @Override
            public ReportDeviceStatusInfoResp parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ReportDeviceStatusInfoResp(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ReportDeviceStatusInfoResp> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<ReportDeviceStatusInfoResp> getParserForType() {
            return PARSER;
        }

        @Override
        public ReportDeviceStatusInfoResp getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\025server_response.proto\022\rcom.nuu.proto\"<" +
                        "\n\032ReportDeviceStatusInfoResp\022\021\n\tdevice_i" +
                        "d\030\001 \001(\t\022\013\n\003utc\030\002 \001(\r"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_nuu_proto_ReportDeviceStatusInfoResp_descriptor,
                new String[]{"DeviceId", "Utc",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
