package com.nuu.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_response.proto

public final class ServerResponse {
    private ServerResponse() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ReportDeviceStatusInfoRespOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ReportDeviceStatusInfoResp)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string device_id = 1;</code>
         */
        boolean hasDeviceId();

        /**
         * <code>optional string device_id = 1;</code>
         */
        String getDeviceId();

        /**
         * <code>optional string device_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getDeviceIdBytes();

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        boolean hasUtc();

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        int getUtc();
    }

    /**
     * Protobuf type {@code ReportDeviceStatusInfoResp}
     */
    public static final class ReportDeviceStatusInfoResp extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ReportDeviceStatusInfoResp)
            ReportDeviceStatusInfoRespOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ReportDeviceStatusInfoResp.newBuilder() to construct.
        private ReportDeviceStatusInfoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ReportDeviceStatusInfoResp() {
            deviceId_ = "";
            utc_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private ReportDeviceStatusInfoResp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            deviceId_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            utc_ = input.readUInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ServerResponse.internal_static_ReportDeviceStatusInfoResp_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ServerResponse.internal_static_ReportDeviceStatusInfoResp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ServerResponse.ReportDeviceStatusInfoResp.class, ServerResponse.ReportDeviceStatusInfoResp.Builder.class);
        }

        private int bitField0_;
        public static final int DEVICE_ID_FIELD_NUMBER = 1;
        private volatile Object deviceId_;

        /**
         * <code>optional string device_id = 1;</code>
         */
        public boolean hasDeviceId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string device_id = 1;</code>
         */
        public String getDeviceId() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    deviceId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string device_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int UTC_FIELD_NUMBER = 2;
        private int utc_;

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        public boolean hasUtc() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional uint32 utc = 2;</code>
         */
        public int getUtc() {
            return utc_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeUInt32(2, utc_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, utc_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ServerResponse.ReportDeviceStatusInfoResp)) {
                return super.equals(obj);
            }
            ServerResponse.ReportDeviceStatusInfoResp other = (ServerResponse.ReportDeviceStatusInfoResp) obj;

            boolean result = true;
            result = result && (hasDeviceId() == other.hasDeviceId());
            if (hasDeviceId()) {
                result = result && getDeviceId()
                        .equals(other.getDeviceId());
            }
            result = result && (hasUtc() == other.hasUtc());
            if (hasUtc()) {
                result = result && (getUtc()
                        == other.getUtc());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasDeviceId()) {
                hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
                hash = (53 * hash) + getDeviceId().hashCode();
            }
            if (hasUtc()) {
                hash = (37 * hash) + UTC_FIELD_NUMBER;
                hash = (53 * hash) + getUtc();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ServerResponse.ReportDeviceStatusInfoResp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ServerResponse.ReportDeviceStatusInfoResp prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ReportDeviceStatusInfoResp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ReportDeviceStatusInfoResp)
                ServerResponse.ReportDeviceStatusInfoRespOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ServerResponse.internal_static_ReportDeviceStatusInfoResp_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ServerResponse.internal_static_ReportDeviceStatusInfoResp_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ServerResponse.ReportDeviceStatusInfoResp.class, ServerResponse.ReportDeviceStatusInfoResp.Builder.class);
            }

            // Construct using ServerResponse.ReportDeviceStatusInfoResp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                deviceId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                utc_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ServerResponse.internal_static_ReportDeviceStatusInfoResp_descriptor;
            }

            @Override
            public ServerResponse.ReportDeviceStatusInfoResp getDefaultInstanceForType() {
                return ServerResponse.ReportDeviceStatusInfoResp.getDefaultInstance();
            }

            @Override
            public ServerResponse.ReportDeviceStatusInfoResp build() {
                ServerResponse.ReportDeviceStatusInfoResp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public ServerResponse.ReportDeviceStatusInfoResp buildPartial() {
                ServerResponse.ReportDeviceStatusInfoResp result = new ServerResponse.ReportDeviceStatusInfoResp(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.deviceId_ = deviceId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.utc_ = utc_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ServerResponse.ReportDeviceStatusInfoResp) {
                    return mergeFrom((ServerResponse.ReportDeviceStatusInfoResp) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ServerResponse.ReportDeviceStatusInfoResp other) {
                if (other == ServerResponse.ReportDeviceStatusInfoResp.getDefaultInstance())
                    return this;
                if (other.hasDeviceId()) {
                    bitField0_ |= 0x00000001;
                    deviceId_ = other.deviceId_;
                    onChanged();
                }
                if (other.hasUtc()) {
                    setUtc(other.getUtc());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ServerResponse.ReportDeviceStatusInfoResp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ServerResponse.ReportDeviceStatusInfoResp) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Object deviceId_ = "";

            /**
             * <code>optional string device_id = 1;</code>
             */
            public boolean hasDeviceId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public String getDeviceId() {
                Object ref = deviceId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        deviceId_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getDeviceIdBytes() {
                Object ref = deviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    deviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public Builder setDeviceId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                deviceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public Builder clearDeviceId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                deviceId_ = getDefaultInstance().getDeviceId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string device_id = 1;</code>
             */
            public Builder setDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                deviceId_ = value;
                onChanged();
                return this;
            }

            private int utc_;

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public boolean hasUtc() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public int getUtc() {
                return utc_;
            }

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public Builder setUtc(int value) {
                bitField0_ |= 0x00000002;
                utc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 utc = 2;</code>
             */
            public Builder clearUtc() {
                bitField0_ = (bitField0_ & ~0x00000002);
                utc_ = 0;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ReportDeviceStatusInfoResp)
        }

        // @@protoc_insertion_point(class_scope:ReportDeviceStatusInfoResp)
        private static final ServerResponse.ReportDeviceStatusInfoResp DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ServerResponse.ReportDeviceStatusInfoResp();
        }

        public static ServerResponse.ReportDeviceStatusInfoResp getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<ReportDeviceStatusInfoResp>
                PARSER = new com.google.protobuf.AbstractParser<ReportDeviceStatusInfoResp>() {
            @Override
            public ReportDeviceStatusInfoResp parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ReportDeviceStatusInfoResp(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ReportDeviceStatusInfoResp> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<ReportDeviceStatusInfoResp> getParserForType() {
            return PARSER;
        }

        @Override
        public ServerResponse.ReportDeviceStatusInfoResp getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ReportDeviceStatusInfoResp_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ReportDeviceStatusInfoResp_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\025server_response.proto\"<\n\032ReportDeviceS" +
                        "tatusInfoResp\022\021\n\tdevice_id\030\001 \001(\t\022\013\n\003utc\030" +
                        "\002 \001(\r"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_ReportDeviceStatusInfoResp_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ReportDeviceStatusInfoResp_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ReportDeviceStatusInfoResp_descriptor,
                new String[]{"DeviceId", "Utc",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
