package com.nuu.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_request.proto

public final class UpdateRequest {
    private UpdateRequest() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface DeviceUpgradeReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DeviceUpgradeReq)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string devId = 1;</code>
         */
        boolean hasDevId();

        /**
         * <code>optional string devId = 1;</code>
         */
        String getDevId();

        /**
         * <code>optional string devId = 1;</code>
         */
        com.google.protobuf.ByteString
        getDevIdBytes();

        /**
         * <code>optional string curVerCode = 2;</code>
         */
        boolean hasCurVerCode();

        /**
         * <code>optional string curVerCode = 2;</code>
         */
        String getCurVerCode();

        /**
         * <code>optional string curVerCode = 2;</code>
         */
        com.google.protobuf.ByteString
        getCurVerCodeBytes();

        /**
         * <code>optional string brand = 3;</code>
         */
        boolean hasBrand();

        /**
         * <code>optional string brand = 3;</code>
         */
        String getBrand();

        /**
         * <code>optional string brand = 3;</code>
         */
        com.google.protobuf.ByteString
        getBrandBytes();

        /**
         * <code>optional string model = 4;</code>
         */
        boolean hasModel();

        /**
         * <code>optional string model = 4;</code>
         */
        String getModel();

        /**
         * <code>optional string model = 4;</code>
         */
        com.google.protobuf.ByteString
        getModelBytes();
    }

    /**
     * Protobuf type {@code DeviceUpgradeReq}
     */
    public static final class DeviceUpgradeReq extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:DeviceUpgradeReq)
            DeviceUpgradeReqOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use DeviceUpgradeReq.newBuilder() to construct.
        private DeviceUpgradeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private DeviceUpgradeReq() {
            devId_ = "";
            curVerCode_ = "";
            brand_ = "";
            model_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private DeviceUpgradeReq(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            devId_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            curVerCode_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            brand_ = bs;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000008;
                            model_ = bs;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return UpdateRequest.internal_static_DeviceUpgradeReq_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return UpdateRequest.internal_static_DeviceUpgradeReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UpdateRequest.DeviceUpgradeReq.class, UpdateRequest.DeviceUpgradeReq.Builder.class);
        }

        private int bitField0_;
        public static final int DEVID_FIELD_NUMBER = 1;
        private volatile Object devId_;

        /**
         * <code>optional string devId = 1;</code>
         */
        public boolean hasDevId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string devId = 1;</code>
         */
        public String getDevId() {
            Object ref = devId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    devId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string devId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDevIdBytes() {
            Object ref = devId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                devId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CURVERCODE_FIELD_NUMBER = 2;
        private volatile Object curVerCode_;

        /**
         * <code>optional string curVerCode = 2;</code>
         */
        public boolean hasCurVerCode() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string curVerCode = 2;</code>
         */
        public String getCurVerCode() {
            Object ref = curVerCode_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    curVerCode_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string curVerCode = 2;</code>
         */
        public com.google.protobuf.ByteString
        getCurVerCodeBytes() {
            Object ref = curVerCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                curVerCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BRAND_FIELD_NUMBER = 3;
        private volatile Object brand_;

        /**
         * <code>optional string brand = 3;</code>
         */
        public boolean hasBrand() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string brand = 3;</code>
         */
        public String getBrand() {
            Object ref = brand_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    brand_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string brand = 3;</code>
         */
        public com.google.protobuf.ByteString
        getBrandBytes() {
            Object ref = brand_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                brand_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int MODEL_FIELD_NUMBER = 4;
        private volatile Object model_;

        /**
         * <code>optional string model = 4;</code>
         */
        public boolean hasModel() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional string model = 4;</code>
         */
        public String getModel() {
            Object ref = model_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    model_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string model = 4;</code>
         */
        public com.google.protobuf.ByteString
        getModelBytes() {
            Object ref = model_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                model_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, devId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, curVerCode_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, brand_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, model_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, devId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, curVerCode_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, brand_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, model_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof UpdateRequest.DeviceUpgradeReq)) {
                return super.equals(obj);
            }
            UpdateRequest.DeviceUpgradeReq other = (UpdateRequest.DeviceUpgradeReq) obj;

            boolean result = true;
            result = result && (hasDevId() == other.hasDevId());
            if (hasDevId()) {
                result = result && getDevId()
                        .equals(other.getDevId());
            }
            result = result && (hasCurVerCode() == other.hasCurVerCode());
            if (hasCurVerCode()) {
                result = result && getCurVerCode()
                        .equals(other.getCurVerCode());
            }
            result = result && (hasBrand() == other.hasBrand());
            if (hasBrand()) {
                result = result && getBrand()
                        .equals(other.getBrand());
            }
            result = result && (hasModel() == other.hasModel());
            if (hasModel()) {
                result = result && getModel()
                        .equals(other.getModel());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasDevId()) {
                hash = (37 * hash) + DEVID_FIELD_NUMBER;
                hash = (53 * hash) + getDevId().hashCode();
            }
            if (hasCurVerCode()) {
                hash = (37 * hash) + CURVERCODE_FIELD_NUMBER;
                hash = (53 * hash) + getCurVerCode().hashCode();
            }
            if (hasBrand()) {
                hash = (37 * hash) + BRAND_FIELD_NUMBER;
                hash = (53 * hash) + getBrand().hashCode();
            }
            if (hasModel()) {
                hash = (37 * hash) + MODEL_FIELD_NUMBER;
                hash = (53 * hash) + getModel().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeReq parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static UpdateRequest.DeviceUpgradeReq parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UpdateRequest.DeviceUpgradeReq parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(UpdateRequest.DeviceUpgradeReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code DeviceUpgradeReq}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:DeviceUpgradeReq)
                UpdateRequest.DeviceUpgradeReqOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return UpdateRequest.internal_static_DeviceUpgradeReq_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return UpdateRequest.internal_static_DeviceUpgradeReq_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UpdateRequest.DeviceUpgradeReq.class, UpdateRequest.DeviceUpgradeReq.Builder.class);
            }

            // Construct using UpdateRequest.DeviceUpgradeReq.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                devId_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                curVerCode_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                brand_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                model_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return UpdateRequest.internal_static_DeviceUpgradeReq_descriptor;
            }

            @Override
            public UpdateRequest.DeviceUpgradeReq getDefaultInstanceForType() {
                return UpdateRequest.DeviceUpgradeReq.getDefaultInstance();
            }

            @Override
            public UpdateRequest.DeviceUpgradeReq build() {
                UpdateRequest.DeviceUpgradeReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public UpdateRequest.DeviceUpgradeReq buildPartial() {
                UpdateRequest.DeviceUpgradeReq result = new UpdateRequest.DeviceUpgradeReq(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.devId_ = devId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.curVerCode_ = curVerCode_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.brand_ = brand_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.model_ = model_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof UpdateRequest.DeviceUpgradeReq) {
                    return mergeFrom((UpdateRequest.DeviceUpgradeReq) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(UpdateRequest.DeviceUpgradeReq other) {
                if (other == UpdateRequest.DeviceUpgradeReq.getDefaultInstance()) return this;
                if (other.hasDevId()) {
                    bitField0_ |= 0x00000001;
                    devId_ = other.devId_;
                    onChanged();
                }
                if (other.hasCurVerCode()) {
                    bitField0_ |= 0x00000002;
                    curVerCode_ = other.curVerCode_;
                    onChanged();
                }
                if (other.hasBrand()) {
                    bitField0_ |= 0x00000004;
                    brand_ = other.brand_;
                    onChanged();
                }
                if (other.hasModel()) {
                    bitField0_ |= 0x00000008;
                    model_ = other.model_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                UpdateRequest.DeviceUpgradeReq parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (UpdateRequest.DeviceUpgradeReq) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Object devId_ = "";

            /**
             * <code>optional string devId = 1;</code>
             */
            public boolean hasDevId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string devId = 1;</code>
             */
            public String getDevId() {
                Object ref = devId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        devId_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string devId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getDevIdBytes() {
                Object ref = devId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    devId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string devId = 1;</code>
             */
            public Builder setDevId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                devId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string devId = 1;</code>
             */
            public Builder clearDevId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                devId_ = getDefaultInstance().getDevId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string devId = 1;</code>
             */
            public Builder setDevIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                devId_ = value;
                onChanged();
                return this;
            }

            private Object curVerCode_ = "";

            /**
             * <code>optional string curVerCode = 2;</code>
             */
            public boolean hasCurVerCode() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string curVerCode = 2;</code>
             */
            public String getCurVerCode() {
                Object ref = curVerCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        curVerCode_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string curVerCode = 2;</code>
             */
            public com.google.protobuf.ByteString
            getCurVerCodeBytes() {
                Object ref = curVerCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    curVerCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string curVerCode = 2;</code>
             */
            public Builder setCurVerCode(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                curVerCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string curVerCode = 2;</code>
             */
            public Builder clearCurVerCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                curVerCode_ = getDefaultInstance().getCurVerCode();
                onChanged();
                return this;
            }

            /**
             * <code>optional string curVerCode = 2;</code>
             */
            public Builder setCurVerCodeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                curVerCode_ = value;
                onChanged();
                return this;
            }

            private Object brand_ = "";

            /**
             * <code>optional string brand = 3;</code>
             */
            public boolean hasBrand() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string brand = 3;</code>
             */
            public String getBrand() {
                Object ref = brand_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        brand_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string brand = 3;</code>
             */
            public com.google.protobuf.ByteString
            getBrandBytes() {
                Object ref = brand_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    brand_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string brand = 3;</code>
             */
            public Builder setBrand(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                brand_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string brand = 3;</code>
             */
            public Builder clearBrand() {
                bitField0_ = (bitField0_ & ~0x00000004);
                brand_ = getDefaultInstance().getBrand();
                onChanged();
                return this;
            }

            /**
             * <code>optional string brand = 3;</code>
             */
            public Builder setBrandBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                brand_ = value;
                onChanged();
                return this;
            }

            private Object model_ = "";

            /**
             * <code>optional string model = 4;</code>
             */
            public boolean hasModel() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional string model = 4;</code>
             */
            public String getModel() {
                Object ref = model_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        model_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string model = 4;</code>
             */
            public com.google.protobuf.ByteString
            getModelBytes() {
                Object ref = model_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    model_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string model = 4;</code>
             */
            public Builder setModel(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                model_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string model = 4;</code>
             */
            public Builder clearModel() {
                bitField0_ = (bitField0_ & ~0x00000008);
                model_ = getDefaultInstance().getModel();
                onChanged();
                return this;
            }

            /**
             * <code>optional string model = 4;</code>
             */
            public Builder setModelBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                model_ = value;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:DeviceUpgradeReq)
        }

        // @@protoc_insertion_point(class_scope:DeviceUpgradeReq)
        private static final UpdateRequest.DeviceUpgradeReq DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new UpdateRequest.DeviceUpgradeReq();
        }

        public static UpdateRequest.DeviceUpgradeReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<DeviceUpgradeReq>
                PARSER = new com.google.protobuf.AbstractParser<DeviceUpgradeReq>() {
            @Override
            public DeviceUpgradeReq parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DeviceUpgradeReq(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DeviceUpgradeReq> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<DeviceUpgradeReq> getParserForType() {
            return PARSER;
        }

        @Override
        public UpdateRequest.DeviceUpgradeReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface DeviceUpgradeRespOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DeviceUpgradeResp)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bool result = 1;</code>
         */
        boolean hasResult();

        /**
         * <code>required bool result = 1;</code>
         */
        boolean getResult();

        /**
         * <code>optional string newVerCode = 2;</code>
         */
        boolean hasNewVerCode();

        /**
         * <code>optional string newVerCode = 2;</code>
         */
        String getNewVerCode();

        /**
         * <code>optional string newVerCode = 2;</code>
         */
        com.google.protobuf.ByteString
        getNewVerCodeBytes();

        /**
         * <code>optional string url = 3;</code>
         */
        boolean hasUrl();

        /**
         * <code>optional string url = 3;</code>
         */
        String getUrl();

        /**
         * <code>optional string url = 3;</code>
         */
        com.google.protobuf.ByteString
        getUrlBytes();
    }

    /**
     * Protobuf type {@code DeviceUpgradeResp}
     */
    public static final class DeviceUpgradeResp extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:DeviceUpgradeResp)
            DeviceUpgradeRespOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use DeviceUpgradeResp.newBuilder() to construct.
        private DeviceUpgradeResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private DeviceUpgradeResp() {
            result_ = false;
            newVerCode_ = "";
            url_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private DeviceUpgradeResp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readBool();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            newVerCode_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            url_ = bs;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return UpdateRequest.internal_static_DeviceUpgradeResp_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return UpdateRequest.internal_static_DeviceUpgradeResp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UpdateRequest.DeviceUpgradeResp.class, UpdateRequest.DeviceUpgradeResp.Builder.class);
        }

        private int bitField0_;
        public static final int RESULT_FIELD_NUMBER = 1;
        private boolean result_;

        /**
         * <code>required bool result = 1;</code>
         */
        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bool result = 1;</code>
         */
        public boolean getResult() {
            return result_;
        }

        public static final int NEWVERCODE_FIELD_NUMBER = 2;
        private volatile Object newVerCode_;

        /**
         * <code>optional string newVerCode = 2;</code>
         */
        public boolean hasNewVerCode() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string newVerCode = 2;</code>
         */
        public String getNewVerCode() {
            Object ref = newVerCode_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    newVerCode_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string newVerCode = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNewVerCodeBytes() {
            Object ref = newVerCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                newVerCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int URL_FIELD_NUMBER = 3;
        private volatile Object url_;

        /**
         * <code>optional string url = 3;</code>
         */
        public boolean hasUrl() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string url = 3;</code>
         */
        public String getUrl() {
            Object ref = url_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    url_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string url = 3;</code>
         */
        public com.google.protobuf.ByteString
        getUrlBytes() {
            Object ref = url_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                url_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasResult()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBool(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newVerCode_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newVerCode_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof UpdateRequest.DeviceUpgradeResp)) {
                return super.equals(obj);
            }
            UpdateRequest.DeviceUpgradeResp other = (UpdateRequest.DeviceUpgradeResp) obj;

            boolean result = true;
            result = result && (hasResult() == other.hasResult());
            if (hasResult()) {
                result = result && (getResult()
                        == other.getResult());
            }
            result = result && (hasNewVerCode() == other.hasNewVerCode());
            if (hasNewVerCode()) {
                result = result && getNewVerCode()
                        .equals(other.getNewVerCode());
            }
            result = result && (hasUrl() == other.hasUrl());
            if (hasUrl()) {
                result = result && getUrl()
                        .equals(other.getUrl());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasResult()) {
                hash = (37 * hash) + RESULT_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                        getResult());
            }
            if (hasNewVerCode()) {
                hash = (37 * hash) + NEWVERCODE_FIELD_NUMBER;
                hash = (53 * hash) + getNewVerCode().hashCode();
            }
            if (hasUrl()) {
                hash = (37 * hash) + URL_FIELD_NUMBER;
                hash = (53 * hash) + getUrl().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeResp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static UpdateRequest.DeviceUpgradeResp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static UpdateRequest.DeviceUpgradeResp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(UpdateRequest.DeviceUpgradeResp prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code DeviceUpgradeResp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:DeviceUpgradeResp)
                UpdateRequest.DeviceUpgradeRespOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return UpdateRequest.internal_static_DeviceUpgradeResp_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return UpdateRequest.internal_static_DeviceUpgradeResp_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                UpdateRequest.DeviceUpgradeResp.class, UpdateRequest.DeviceUpgradeResp.Builder.class);
            }

            // Construct using UpdateRequest.DeviceUpgradeResp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                result_ = false;
                bitField0_ = (bitField0_ & ~0x00000001);
                newVerCode_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                url_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return UpdateRequest.internal_static_DeviceUpgradeResp_descriptor;
            }

            @Override
            public UpdateRequest.DeviceUpgradeResp getDefaultInstanceForType() {
                return UpdateRequest.DeviceUpgradeResp.getDefaultInstance();
            }

            @Override
            public UpdateRequest.DeviceUpgradeResp build() {
                UpdateRequest.DeviceUpgradeResp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public UpdateRequest.DeviceUpgradeResp buildPartial() {
                UpdateRequest.DeviceUpgradeResp result = new UpdateRequest.DeviceUpgradeResp(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.newVerCode_ = newVerCode_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.url_ = url_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof UpdateRequest.DeviceUpgradeResp) {
                    return mergeFrom((UpdateRequest.DeviceUpgradeResp) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(UpdateRequest.DeviceUpgradeResp other) {
                if (other == UpdateRequest.DeviceUpgradeResp.getDefaultInstance()) return this;
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasNewVerCode()) {
                    bitField0_ |= 0x00000002;
                    newVerCode_ = other.newVerCode_;
                    onChanged();
                }
                if (other.hasUrl()) {
                    bitField0_ |= 0x00000004;
                    url_ = other.url_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!hasResult()) {
                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                UpdateRequest.DeviceUpgradeResp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (UpdateRequest.DeviceUpgradeResp) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private boolean result_;

            /**
             * <code>required bool result = 1;</code>
             */
            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bool result = 1;</code>
             */
            public boolean getResult() {
                return result_;
            }

            /**
             * <code>required bool result = 1;</code>
             */
            public Builder setResult(boolean value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bool result = 1;</code>
             */
            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = false;
                onChanged();
                return this;
            }

            private Object newVerCode_ = "";

            /**
             * <code>optional string newVerCode = 2;</code>
             */
            public boolean hasNewVerCode() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string newVerCode = 2;</code>
             */
            public String getNewVerCode() {
                Object ref = newVerCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        newVerCode_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string newVerCode = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNewVerCodeBytes() {
                Object ref = newVerCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    newVerCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string newVerCode = 2;</code>
             */
            public Builder setNewVerCode(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                newVerCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string newVerCode = 2;</code>
             */
            public Builder clearNewVerCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                newVerCode_ = getDefaultInstance().getNewVerCode();
                onChanged();
                return this;
            }

            /**
             * <code>optional string newVerCode = 2;</code>
             */
            public Builder setNewVerCodeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                newVerCode_ = value;
                onChanged();
                return this;
            }

            private Object url_ = "";

            /**
             * <code>optional string url = 3;</code>
             */
            public boolean hasUrl() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public String getUrl() {
                Object ref = url_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        url_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public com.google.protobuf.ByteString
            getUrlBytes() {
                Object ref = url_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    url_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public Builder setUrl(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                url_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public Builder clearUrl() {
                bitField0_ = (bitField0_ & ~0x00000004);
                url_ = getDefaultInstance().getUrl();
                onChanged();
                return this;
            }

            /**
             * <code>optional string url = 3;</code>
             */
            public Builder setUrlBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                url_ = value;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:DeviceUpgradeResp)
        }

        // @@protoc_insertion_point(class_scope:DeviceUpgradeResp)
        private static final UpdateRequest.DeviceUpgradeResp DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new UpdateRequest.DeviceUpgradeResp();
        }

        public static UpdateRequest.DeviceUpgradeResp getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<DeviceUpgradeResp>
                PARSER = new com.google.protobuf.AbstractParser<DeviceUpgradeResp>() {
            @Override
            public DeviceUpgradeResp parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DeviceUpgradeResp(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<DeviceUpgradeResp> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<DeviceUpgradeResp> getParserForType() {
            return PARSER;
        }

        @Override
        public UpdateRequest.DeviceUpgradeResp getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_DeviceUpgradeReq_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_DeviceUpgradeReq_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_DeviceUpgradeResp_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_DeviceUpgradeResp_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\024update_request.proto\"S\n\020DeviceUpgradeR" +
                        "eq\022\r\n\005devId\030\001 \001(\t\022\022\n\ncurVerCode\030\002 \001(\t\022\r\n" +
                        "\005brand\030\003 \001(\t\022\r\n\005model\030\004 \001(\t\"D\n\021DeviceUpg" +
                        "radeResp\022\016\n\006result\030\001 \002(\010\022\022\n\nnewVerCode\030\002" +
                        " \001(\t\022\013\n\003url\030\003 \001(\t"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_DeviceUpgradeReq_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_DeviceUpgradeReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_DeviceUpgradeReq_descriptor,
                new String[]{"DevId", "CurVerCode", "Brand", "Model",});
        internal_static_DeviceUpgradeResp_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_DeviceUpgradeResp_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_DeviceUpgradeResp_descriptor,
                new String[]{"Result", "NewVerCode", "Url",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
